FROM python:3.6-slim-buster

ENV PIP_NO_CACHE_DIR "true"

RUN pip install --upgrade pip pipenv

COPY Pipfile.lock Pipfile /
RUN pipenv install --dev

COPY strava_to_movember /strava_to_movember

RUN pipenv run flake8 --ignore E402 strava_to_movember
RUN pipenv run yapf -i -r strava_to_movember
